"""baseline_v0_schema_from_models

Revision ID: 8658705d5116
Revises: 
Create Date: 2026-05-27 04:34:02.582818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8658705d5116'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(), nullable=False),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('office', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('race_level', sa.String(), nullable=True),
    sa.Column('election_type', sa.String(), nullable=True),
    sa.Column('district_number', sa.String(), nullable=True),
    sa.Column('neighborhood_keywords', sa.Text(), nullable=True),
    sa.Column('sparse_race_mode', sa.Boolean(), nullable=True),
    sa.Column('election_date', sa.DateTime(), nullable=True),
    sa.Column('campaign_message', sa.Text(), nullable=True),
    sa.Column('key_priorities', sa.Text(), nullable=True),
    sa.Column('relevance_keywords', sa.Text(), nullable=True),
    sa.Column('excluded_keywords', sa.Text(), nullable=True),
    sa.Column('geography_keywords', sa.Text(), nullable=True),
    sa.Column('trends_keywords', sa.Text(), nullable=True),
    sa.Column('historical_backfill_completed', sa.Boolean(), nullable=True),
    sa.Column('extended_backfill_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('seeded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_canonical_id'), ['canonical_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_entities_seeded'), ['seeded'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_type'), ['type'], unique=False)

    op.create_table('entity_review_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_key', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_type', 'item_key', name='uq_entity_review_decision_item')
    )
    with op.batch_alter_table('entity_review_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_review_decisions_item_key'), ['item_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_review_decisions_item_type'), ['item_type'], unique=False)

    op.create_table('gdelt_tone_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_label', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('avg_tone', sa.Float(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_label', 'snapshot_date', name='uq_gdelt_tone_daily')
    )
    op.create_table('google_trend_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('interest', sa.Integer(), nullable=True),
    sa.Column('geo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term', 'snapshot_date', 'geo', name='uq_google_trend_daily')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('manual_source_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('setup_note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrative_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=True),
    sa.Column('subject_type', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_known_stage', sa.String(), nullable=True),
    sa.Column('last_stage_check_at', sa.DateTime(), nullable=True),
    sa.Column('momentum_signal', sa.String(), nullable=True),
    sa.Column('momentum_signal_at', sa.DateTime(), nullable=True),
    sa.Column('momentum_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opponents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('office', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fec_candidate_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fec_candidate_id')
    )
    op.create_table('outlets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('outlet_type', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('authority_score', sa.Integer(), nullable=False),
    sa.Column('rss_url', sa.String(), nullable=True),
    sa.Column('districts', sa.Text(), nullable=True),
    sa.Column('monthly_visitors', sa.Integer(), nullable=True),
    sa.Column('bias_label', sa.String(), nullable=True),
    sa.Column('reliability_score', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('proposed_cluster_triage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_fingerprint', sa.String(), nullable=False),
    sa.Column('member_candidate_frame_ids_json', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('suggested_merge_frame_id', sa.Integer(), nullable=True),
    sa.Column('suggested_name', sa.String(), nullable=True),
    sa.Column('suggested_description', sa.Text(), nullable=True),
    sa.Column('suggested_owner_type', sa.String(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('judged_by_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposed_cluster_triage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposed_cluster_triage_cluster_fingerprint'), ['cluster_fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_proposed_cluster_triage_suggested_merge_frame_id'), ['suggested_merge_frame_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposed_cluster_triage_verdict'), ['verdict'], unique=False)

    op.create_table('race_directory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_key', sa.String(), nullable=False),
    sa.Column('race_name', sa.String(), nullable=False),
    sa.Column('race_level', sa.String(), nullable=False),
    sa.Column('office_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district_label', sa.String(), nullable=True),
    sa.Column('district_number', sa.String(), nullable=True),
    sa.Column('election_type', sa.String(), nullable=False),
    sa.Column('election_date', sa.DateTime(), nullable=True),
    sa.Column('geography_summary', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race_directory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_directory_race_key'), ['race_key'], unique=True)

    op.create_table('race_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('candidate_pct', sa.Float(), nullable=True),
    sa.Column('opponent_pct', sa.Float(), nullable=True),
    sa.Column('delta_7d', sa.Float(), nullable=True),
    sa.Column('rating_label', sa.String(), nullable=True),
    sa.Column('rating_min_pct', sa.Float(), nullable=True),
    sa.Column('rating_max_pct', sa.Float(), nullable=True),
    sa.Column('favors', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('as_of', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('external_metadata', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_table('race_sentiment_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('candidate_pct', sa.Float(), nullable=True),
    sa.Column('opponent_pct', sa.Float(), nullable=True),
    sa.Column('rating_label', sa.String(), nullable=True),
    sa.Column('rating_min_pct', sa.Float(), nullable=True),
    sa.Column('rating_max_pct', sa.Float(), nullable=True),
    sa.Column('favors', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('source_as_of', sa.DateTime(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'captured_at', name='uq_race_sentiment_snapshot')
    )
    with op.batch_alter_table('race_sentiment_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_sentiment_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_sentiment_snapshots_source'), ['source'], unique=False)

    op.create_table('rss_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('source_monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monitor_type', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('required_terms', sa.Text(), nullable=True),
    sa.Column('excluded_terms', sa.Text(), nullable=True),
    sa.Column('relevance_hint', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('race_level', sa.String(), nullable=True),
    sa.Column('geography', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_region_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_frame_ids_json', sa.Text(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('edited_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('procedural', sa.String(), nullable=True),
    sa.Column('rhetorical', sa.String(), nullable=True),
    sa.Column('ideological', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retracted_at', sa.DateTime(), nullable=True),
    sa.Column('retracted_by', sa.String(), nullable=True),
    sa.Column('retracted_reason', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('sample_quote', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('extractor_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'predicate', 'object_id', name='uq_claim_triple')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_predicate'), ['predicate'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_subject_id'), ['subject_id'], unique=False)

    op.create_table('entity_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('sample_quote', sa.Text(), nullable=True),
    sa.Column('source_articles', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'predicate', 'object_id', name='uq_entity_relation_triple')
    )
    with op.batch_alter_table('entity_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_relations_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_relations_predicate'), ['predicate'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_relations_subject_id'), ['subject_id'], unique=False)

    op.create_table('frame_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(), nullable=True),
    sa.Column('to_stage', sa.String(), nullable=False),
    sa.Column('transitioned_at', sa.DateTime(), nullable=True),
    sa.Column('metrics_snapshot', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['narrative_frames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frame_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('centroid_embedding', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['narrative_frames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('race_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(), nullable=False),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('is_incumbent', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('campaign_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race_directory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_owner_type', sa.String(), nullable=True),
    sa.Column('source_owner_confidence', sa.String(), nullable=True),
    sa.Column('source_author', sa.String(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('credibility_note', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('evidence_score', sa.Integer(), nullable=True),
    sa.Column('credibility_score', sa.Integer(), nullable=True),
    sa.Column('race_relevance_score', sa.Integer(), nullable=True),
    sa.Column('race_relevance_label', sa.String(), nullable=True),
    sa.Column('relevance_reasons', sa.Text(), nullable=True),
    sa.Column('actionability_score', sa.Integer(), nullable=True),
    sa.Column('actionability_label', sa.String(), nullable=True),
    sa.Column('content_category', sa.String(), nullable=True),
    sa.Column('geo_relevance', sa.String(), nullable=True),
    sa.Column('candidate_mentioned', sa.Boolean(), nullable=True),
    sa.Column('opponent_mentioned', sa.Boolean(), nullable=True),
    sa.Column('district_mentioned', sa.Boolean(), nullable=True),
    sa.Column('priority_issue_mentioned', sa.Boolean(), nullable=True),
    sa.Column('archived_as_irrelevant', sa.Boolean(), nullable=True),
    sa.Column('story_cluster_id', sa.String(), nullable=True),
    sa.Column('duplicate_of_source_id', sa.Integer(), nullable=True),
    sa.Column('gdelt_themes', sa.Text(), nullable=True),
    sa.Column('extraction_quality_score', sa.Integer(), nullable=True),
    sa.Column('extraction_quality_label', sa.String(), nullable=True),
    sa.Column('extraction_quality_reasons', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('source_credibility', sa.String(), nullable=True),
    sa.Column('gdelt_tone', sa.Text(), nullable=True),
    sa.Column('structured_extraction', sa.Text(), nullable=True),
    sa.Column('outlet_id', sa.Integer(), nullable=True),
    sa.Column('publisher_domain', sa.String(), nullable=True),
    sa.Column('perspective', sa.String(), nullable=True),
    sa.Column('perspective_method', sa.String(), nullable=True),
    sa.Column('perspective_confidence', sa.String(), nullable=True),
    sa.Column('perspective_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_items_publisher_domain'), ['publisher_domain'], unique=False)

    op.create_table('source_pack_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_pack_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('setup_note', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_pack_id'], ['source_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=False),
    sa.Column('suggested_name', sa.String(), nullable=False),
    sa.Column('owner_type_hint', sa.String(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('resolved_to_frame_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_to_frame_id'], ['narrative_frames.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('evidence_span', sa.Text(), nullable=False),
    sa.Column('evidence_start_char', sa.Integer(), nullable=True),
    sa.Column('evidence_end_char', sa.Integer(), nullable=True),
    sa.Column('evidence_hash', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('extractor_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['source_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_hash', name='uq_claim_record_evidence_hash')
    )
    with op.batch_alter_table('claim_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_records_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_records_evidence_hash'), ['evidence_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_records_extractor_version'), ['extractor_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_records_label'), ['label'], unique=False)

    op.create_table('claim_supports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('stance', sa.String(), nullable=False),
    sa.Column('sample_quote', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('extractor_version', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['source_items.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'article_id', name='uq_claim_support_pair')
    )
    with op.batch_alter_table('claim_supports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_supports_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_supports_claim_id'), ['claim_id'], unique=False)

    op.create_table('entity_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('surface_text', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('extraction_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['source_items.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'entity_id', name='uq_entity_mention_article_entity')
    )
    with op.batch_alter_table('entity_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_mentions_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_mentions_entity_id'), ['entity_id'], unique=False)

    op.create_table('issue_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=False),
    sa.Column('link_strength', sa.Integer(), nullable=True),
    sa.Column('link_reasons', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('narrative_frame_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('matched_by', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('claim_meta', sa.Text(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quote_embedding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['narrative_frames.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['frame_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frame_id', 'source_item_id', name='uq_nfm_frame_source')
    )
    op.create_table('opponent_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=True),
    sa.Column('claim', sa.Text(), nullable=True),
    sa.Column('attack', sa.Text(), nullable=True),
    sa.Column('promise', sa.Text(), nullable=True),
    sa.Column('contradiction_note', sa.Text(), nullable=True),
    sa.Column('repeated_theme', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opponent_id'], ['opponents.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_clusters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seed_source_item_id', sa.Integer(), nullable=False),
    sa.Column('representative_source_item_id', sa.Integer(), nullable=False),
    sa.Column('analysis_anchor_source_item_id', sa.Integer(), nullable=True),
    sa.Column('analysis_anchor_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_llm_analysis_at', sa.DateTime(), nullable=True),
    sa.Column('title_representative', sa.String(), nullable=True),
    sa.Column('summary_representative', sa.Text(), nullable=True),
    sa.Column('simhash_64', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('outlet_count', sa.Integer(), nullable=True),
    sa.Column('source_diversity_score', sa.Float(), nullable=True),
    sa.Column('known_entities', sa.Text(), nullable=True),
    sa.Column('dormant_since', sa.DateTime(), nullable=True),
    sa.Column('structured_extraction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_anchor_source_item_id'], ['source_items.id'], ),
    sa.ForeignKeyConstraint(['representative_source_item_id'], ['source_items.id'], ),
    sa.ForeignKeyConstraint(['seed_source_item_id'], ['source_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_record_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_record_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('surface_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_record_id'], ['claim_records.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_record_id', 'entity_id', name='uq_claim_record_entity_pair')
    )
    with op.batch_alter_table('claim_record_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_record_entities_claim_record_id'), ['claim_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_record_entities_entity_id'), ['entity_id'], unique=False)

    op.create_table('cluster_opponent_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('story_cluster_id', sa.String(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=True),
    sa.Column('attack', sa.Text(), nullable=True),
    sa.Column('promise', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opponent_id'], ['opponents.id'], ),
    sa.ForeignKeyConstraint(['story_cluster_id'], ['story_clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opponent_id', 'story_cluster_id', 'fingerprint', name='uq_cluster_opponent_fp')
    )
    op.create_table('frame_cluster_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=False),
    sa.Column('story_cluster_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('matched_by', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('representative_snapshot_ts', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['narrative_frames.id'], ),
    sa.ForeignKeyConstraint(['story_cluster_id'], ['story_clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frame_id', 'story_cluster_id', name='uq_frame_cluster')
    )
    # ### end Alembic commands ###

    # Indexes added by the legacy _migrate() block in app/db.py — not declared
    # in models.py so autogenerate didn't see them, but they exist on the live
    # SQLite DB and the production Postgres needs them for query performance.
    # Should eventually be moved into __table_args__ on the relevant models so
    # autogenerate picks them up; doing that here would race the concurrent
    # v15.0 work on models.py.
    op.create_index('ix_story_clusters_last_seen_at', 'story_clusters', ['last_seen_at'])
    op.create_index('ix_story_clusters_first_seen_at', 'story_clusters', ['first_seen_at'])
    op.create_index('ix_story_clusters_representative', 'story_clusters', ['representative_source_item_id'])
    op.create_index('ix_story_clusters_simhash_lastseen', 'story_clusters', ['simhash_64', 'last_seen_at'])
    op.create_index('ix_fcm_frame_id', 'frame_cluster_matches', ['frame_id'])
    op.create_index('ix_fcm_cluster_id', 'frame_cluster_matches', ['story_cluster_id'])
    op.create_index('ix_fcm_first_seen', 'frame_cluster_matches', ['first_seen_at'])
    op.create_index('ix_coa_opponent_id', 'cluster_opponent_activities', ['opponent_id'])
    op.create_index('ix_coa_cluster_id', 'cluster_opponent_activities', ['story_cluster_id'])
    op.create_index('ix_fsh_frame_transitioned', 'frame_stage_history', ['frame_id', 'transitioned_at'])
    op.create_index('ix_fv_frame_id', 'frame_variants', ['frame_id'])


def downgrade() -> None:
    # Drop the manually-added (from _migrate()) indexes first, in reverse order.
    op.drop_index('ix_fv_frame_id', table_name='frame_variants')
    op.drop_index('ix_fsh_frame_transitioned', table_name='frame_stage_history')
    op.drop_index('ix_coa_cluster_id', table_name='cluster_opponent_activities')
    op.drop_index('ix_coa_opponent_id', table_name='cluster_opponent_activities')
    op.drop_index('ix_fcm_first_seen', table_name='frame_cluster_matches')
    op.drop_index('ix_fcm_cluster_id', table_name='frame_cluster_matches')
    op.drop_index('ix_fcm_frame_id', table_name='frame_cluster_matches')
    op.drop_index('ix_story_clusters_simhash_lastseen', table_name='story_clusters')
    op.drop_index('ix_story_clusters_representative', table_name='story_clusters')
    op.drop_index('ix_story_clusters_first_seen_at', table_name='story_clusters')
    op.drop_index('ix_story_clusters_last_seen_at', table_name='story_clusters')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frame_cluster_matches')
    op.drop_table('cluster_opponent_activities')
    with op.batch_alter_table('claim_record_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_record_entities_entity_id'))
        batch_op.drop_index(batch_op.f('ix_claim_record_entities_claim_record_id'))

    op.drop_table('claim_record_entities')
    op.drop_table('story_clusters')
    op.drop_table('opponent_activities')
    op.drop_table('narrative_frame_mentions')
    op.drop_table('issue_mentions')
    with op.batch_alter_table('entity_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_mentions_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_mentions_article_id'))

    op.drop_table('entity_mentions')
    with op.batch_alter_table('claim_supports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_supports_claim_id'))
        batch_op.drop_index(batch_op.f('ix_claim_supports_article_id'))

    op.drop_table('claim_supports')
    with op.batch_alter_table('claim_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_records_label'))
        batch_op.drop_index(batch_op.f('ix_claim_records_extractor_version'))
        batch_op.drop_index(batch_op.f('ix_claim_records_evidence_hash'))
        batch_op.drop_index(batch_op.f('ix_claim_records_article_id'))

    op.drop_table('claim_records')
    op.drop_table('candidate_frames')
    op.drop_table('source_pack_items')
    with op.batch_alter_table('source_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_items_publisher_domain'))

    op.drop_table('source_items')
    op.drop_table('race_candidates')
    op.drop_table('frame_variants')
    op.drop_table('frame_stage_history')
    with op.batch_alter_table('entity_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_relations_subject_id'))
        batch_op.drop_index(batch_op.f('ix_entity_relations_predicate'))
        batch_op.drop_index(batch_op.f('ix_entity_relations_object_id'))

    op.drop_table('entity_relations')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_subject_id'))
        batch_op.drop_index(batch_op.f('ix_claims_predicate'))
        batch_op.drop_index(batch_op.f('ix_claims_object_id'))

    op.drop_table('claims')
    op.drop_table('topic_region_labels')
    op.drop_table('source_packs')
    op.drop_table('source_monitors')
    op.drop_table('rss_feeds')
    with op.batch_alter_table('race_sentiment_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_sentiment_snapshots_source'))
        batch_op.drop_index(batch_op.f('ix_race_sentiment_snapshots_captured_at'))

    op.drop_table('race_sentiment_snapshots')
    op.drop_table('race_sentiment')
    with op.batch_alter_table('race_directory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_directory_race_key'))

    op.drop_table('race_directory')
    with op.batch_alter_table('proposed_cluster_triage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposed_cluster_triage_verdict'))
        batch_op.drop_index(batch_op.f('ix_proposed_cluster_triage_suggested_merge_frame_id'))
        batch_op.drop_index(batch_op.f('ix_proposed_cluster_triage_cluster_fingerprint'))

    op.drop_table('proposed_cluster_triage')
    op.drop_table('outlets')
    op.drop_table('opponents')
    op.drop_table('narrative_frames')
    op.drop_table('manual_source_reminders')
    op.drop_table('issues')
    op.drop_table('google_trend_snapshots')
    op.drop_table('gdelt_tone_snapshots')
    with op.batch_alter_table('entity_review_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_review_decisions_item_type'))
        batch_op.drop_index(batch_op.f('ix_entity_review_decisions_item_key'))

    op.drop_table('entity_review_decisions')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_type'))
        batch_op.drop_index(batch_op.f('ix_entities_seeded'))
        batch_op.drop_index(batch_op.f('ix_entities_canonical_id'))

    op.drop_table('entities')
    op.drop_table('campaign_config')
    # ### end Alembic commands ###
